name: ssc-scvi
channels: [conda-forge]
dependencies:
  - python=3.10
  - scanpy>=1.9
  - scvi-tools>=1.1
  - anndata
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - jupyterlab
  - requests
  - pip
  - pip:
    - gprofiler-official
    - scrublet
    - GEOparse
